<?
$PERM["video"]["*"]="R";
$PERM["vendors"]["8"]="W";
$PERM["personal"]["8"]="W";
$PERM["reviews"]["8"]="W";
$PERM["desktop_app"]["*"]="D";
$PERM["promotions"]["8"]="W";
$PERM["news"]["8"]="W";
$PERM["catalog"]["8"]="W";
$PERM["index.php"]["8"]="W";
$PERM["/"]["*"]="R";
?>