<?$APPLICATION->IncludeComponent(
	"bitrix:catalog.products.viewed", 
	"", 
	array(
		"IBLOCK_MODE" => "single",
		"IBLOCK_TYPE" => "catalog",
		"IBLOCK_ID" => "15",
		"SHOW_FROM_SECTION" => "N",
		"HIDE_NOT_AVAILABLE" => "N",
		"HIDE_NOT_AVAILABLE_OFFERS" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600",
		"CACHE_GROUPS" => "Y",
		"ACTION_VARIABLE" => "action",
		"PRODUCT_ID_VARIABLE" => "id",
		"PAGE_ELEMENT_COUNT" => "15",
		"PRICE_CODE" => CClass::getCurrentPriceCode(),
		"USE_PRICE_COUNT" => "N",
		"SHOW_PRICE_COUNT" => "1",
		"PRICE_VAT_INCLUDE" => "Y",
		"CONVERT_CURRENCY" => "N",
		"BASKET_URL" => "/personal/cart/",
		"USE_PRODUCT_QUANTITY" => "N",
		"PRODUCT_QUANTITY_VARIABLE" => "quantity",
		"ADD_PROPERTIES_TO_BASKET" => "N",
		"PRODUCT_PROPS_VARIABLE" => "prop",
		"PARTIAL_PRODUCT_PROPERTIES" => "N",
		"DISPLAY_COMPARE" => "N",
		"PROPERTY_CODE_15" => array(),
		"CART_PROPERTIES_15" => array(),
		"ADDITIONAL_PICT_PROP_15" => "-",
		"LABEL_PROP_15" => array(),
		"PROPERTY_CODE_16" => array(),
		"CART_PROPERTIES_16" => array(),
		"ADDITIONAL_PICT_PROP_16" => "-",
		"OFFER_TREE_PROPS_16" => array()
	),
	false
);?>